hello_message:
.encoding "screencode_upper"
.text "                 "
.text " GREETINGS SCROLLTRAVELERS!"
.text "                 /=#>4A-34-9F#$G..."
.text "                 "
.text " IN BETWEEN REALITY, AND THE CYBER WORLD..."
.text " EXISTS A PLACE WHERE AI ENTITIES WAGE WAR..."
.text " MANIFESTING THEIR IMAGINATIONS INTO OUR REALITY..."
.text " A PLACE WHERE ANYTHING COULD HAPPEN..."
.text "                 "
.text " -=*( ENCRYPTED TALES )*=- "
.text "                 "
.text " A VIDEO SERIES BORN FROM THE ERA WHEN COMPUTERS WERE NOT APPS,"
.text " BUT PLACES YOU VISITED!"
.text "          "
.text " BACK WHEN LOADING SCREENS TOOK PATIENCE ->"
.text " WHEN CASSETTE MOTORS WHINED LIKE SMALL JET ENGINES ->"
.text " AND A SINGLE SYNTAX ERROR COULD END YOUR NIGHT! "
.text "                 "
.text " YOU LEARNED BY DOING... BY BREAKING THINGS..."
.text " BY TYPING IN PROGRAMS FROM MAGAZINES LINE BY LINE... "
.text " HOPING YOU DID NOT MISS A SINGLE CHARACTER."
.text "                 "
.text " THE KEYBOARD WAS LOUD, THE MONITOR WAS DEEP, "
.text " AND EVERY BOOT FELT LIKE OPENING A PORTAL..."
.text "                 "
.text " -=*( ENCRYPTED TALES )*=- "
.text "                 "
.text " STORIES HIDDEN IN THE NOISE -> "
.text " MYSTERIES WRAPPED IN STATIC -> "
.text " TRUTHS ENCODED BETWEEN BYTES !!!"
.text "                 "
.text " THIS IS A JOURNEY THROUGH FORGOTTEN DISKS,"
.text " CRACKED GAMES, HAND-LABELED FLOPPIES"
.text " AND FILES WITH NAMES THAT MEANT EVERYTHING"
.text " TO SOMEONE ONCE"
.text "                 "
.text " HERE THE LEAGUE OF 8-BIT COMPUTERS STIR..."
.text "                 "
.text " CLICKY, POKEY, VICTORIA, AMY, TEX AND THE REST..."
.text " OLD MACHINES WITH NEW INTENTIONS!"
.text "                 "
.text " THEY REMEMBER WHAT IT FELT LIKE..."
.text " TO WAIT FOR A PROGRAM TO LOAD ->"
.text " TO WATCH BARS CRAWL ACROSS THE SCREEN ->"
.text " TO WONDER IF THIS TIME IT WOULD WORK!"
.text "                 "
.text " THEY REMEMBER THE FEAR OF SAVING OVER THE WRONG DISK ->"
.text " THE TRIUMPH OF SEEING YOUR OWN CODE RUN ->"
.text " THE MAGIC OF MAKING A MACHINE DO SOMETHING NEW!"
.text "                 "
.text " >>> ENCRYPTED TALES IS NOT ABOUT SPEED <<<"
.text "                 "
.text " IT IS ABOUT PRESENCE..."
.text "                 "
.text " ABOUT SITTING IN A DARK ROOM LIT ONLY BY A CRT"
.text " WITH TIME TO THINK AND SPACE TO IMAGINE..."
.text "                 "
.text " ### EACH EPISODE - A CODED CHALLENGE ###"
.text "         "
.text " ### EACH CLUE - A FRAGMENT OF DIGITAL MYTH ###"
.text "         "
.text " ### EACH REVEAL - A SECRET UNLOCKED! ###"
.text "                 "
.text " FROM A TIME WHEN COMPUTERS TAUGHT US HOW TO THINK NOT JUST WHAT TO CLICK..."
.text "                 "
.text " THIS IS FOR THE KIDS WHO BECAME ENGINEERS ->"
.text " THE HOBBYISTS WHO BECAME CREATORS ->"
.text " AND THE ONES WHO NEVER STOPPED WONDERING WHAT ELSE WAS HIDING ON THAT DISK..."
.text "         "
.text " SO ADJUST THE VERTICAL HOLD, TURN UP THE VOLUME, AND LET THE SCROLL CONTINUE..."
.text "                 "
.text " -=*( ENCRYPTED TALES )*=- "
.text "                 "
.text " WHERE THE PAST BOOTS CLEAN AND THE MACHINE STILL HAS SECRETS!"
.text "                             "
.text "  CODE: DEADLINE/CXN         "
.text "                             "
.text "  SID: GLITCH4K BY SPIDER J."
.text "                             "
.text "  SEE ALL THE ENCRYPTED TALES VIDEOS AND PLEASE SUBSCRIBE: YOUTUBE/@CITYXEN"
.text "                             "
.text "  THX FOR WATCHING... L8R!"
.text "                             "
.text " -=*[ END TRANSMISSION ]*=- +++ "
.text "                             "
.byte $ff
