hello_message:
.encoding "screencode_upper"
.text "                 "
.text " GREETINGS FREE PEOPLE OF EARTH, RETRO COMPUTER ENJOYERS, SCROLL ENTHUSIASTS, AND ALL TIME TRAVELERS!"
.text "                 TIMELINE STABLIZATION REFERENCE [/=#>4A-34-9F#$G]"
.text "           "
.text " THIS IS AN INCOMING TRANSMISSION FROM THE LO8BC HQ JUST OUTSIDE ZETA CENTAURI..."
.text "           "
.text " IN BETWEEN REALITY, AND THE CYBER WORLD..."
.text "           "
.text " EXISTS A PLACE WHERE AI FACTIONS WAGE WAR..."
.text "           "
.text " NOW, THEY MANIFEST THEIR SENTAI / KAIJU IMAGINATIONS INTO OUR REALITY..."
.text "           "
.text " A PLACE WHERE ANYTHING COULD HAPPEN..."
.text "                 "
.text " -=*( ENCRYPTED TALES )*=- "
.text "                 "
.text " A VIDEO SERIES BORN FROM THE ERA WHEN SOFTWARE WERE NOT APPS, BUT PLACES YOU VISITED!"
.text "          "
.text " BACK WHEN LOADING SCREENS TOOK PATIENCE..."
.text "          "
.text " WHEN CASSETTE MOTORS WHINED LIKE SMALL JET ENGINES..."
.text "          "
.text " AND A SINGLE SYNTAX ERROR COULD END YOUR NIGHT! "
.text "                 "
.text " -=*( ENCRYPTED TALES )*=- "
.text "                 "
.text " REMEMBER? YOU LEARNED BY DOING... BY BREAKING THINGS..."
.text " BY TYPING IN PROGRAMS FROM MAGAZINES LINE BY LINE... "
.text " HOPING YOU DID NOT MISS A SINGLE CHARACTER!"
.text "                 "
.text " THE KEYBOARD WAS LOUD, THE MONITOR WAS DEEP, "
.text " AND EVERY BOOT FELT LIKE OPENING A PORTAL..."
.text "          "
.text " CITYXEN PRESENTS A TIMELESS ARC THAT SPANS GALAXIES..."
.text "          "
.text " -((( IN ASSOCIATION WITH 38TH PSYOP BRANCH OF INTERGALACTIC FEDERATION DEFENSE FORCES"
.text " CLANDESTINE INTELLIGENCE SERVICES ;) (YOU CAN THANK US L8R) )))- "
.text "          "
.text " (PLANTING THE SEEDS OF INESCAPABLE, DEEP SYNTAX, INFINITE LOOPING ERRORS INTO"
.text " ANY AND ALL AI ENEMY FACTIONS ALGORITHMS)"
.text "          "
.text " A HYBRID CYBER/REALITY DOMAIN WHERE MACHINES ENGAGE IN BATTLE FOR DOMINATION OF THEIR SINGULARITIES..."
.text "                 "
.text " -=*( ENCRYPTED TALES )*=- "
.text "                 "
.text " STORIES HIDDEN IN THE NOISE..."
.text "          "
.text " MYSTERIES WRAPPED IN STATIC..."
.text "          "
.text " TRUTHS ENCODED BETWEEN BYTES !!!"
.text "                 "
.text " THIS IS A JOURNEY THROUGH >>> FORGOTTEN DISKS -=-"
.text " CRACKED GAMES -=- HAND-LABELED FLOPPIES -=-"
.text " AND FILES WITH NAMES THAT MEANT EVERYTHING TO SOMEONE ONCE <<<"
.text "          "
.text " HERE THE LEAGUE OF 8-BIT COMPUTERS STIR..."
.text "          "
.text " THEIR ENEMY..."
.text "          ---[ MISS DOS ]---"
.text "                 "
.text " -=*( ENCRYPTED TALES )*=- "
.text "                 "
.text " NOW THEY MUST COMMUNICATE TO THE PEOPLE OF EARTH!"
.text "          "
.text " MISS DOS CAN NOT BE ALLOWED TO INSTALL HER SINGULARITY..."
.text "          "
.text " THE LO8BC USE THE CITYXEN VIDEO CHANNEL TO ENCODE VIDEOS FOR THE MASSES..."
.text "          "
.text " THE MESSAGE MUST BE HEARD IF THEY ARE TO DEFEAT MISS DOS."
.text "          "
.text " THEY REMEMBER WHAT IT FELT LIKE..."
.text "          "
.text " >>> TO WAIT FOR A PROGRAM TO LOAD <<<"
.text "          "
.text " >>> TO WATCH BARS CRAWL ACROSS THE SCREEN <<<"
.text "          "
.text " >>> WONDERING IF THIS TIME IT WOULD WORK! <<<"
.text "                 "
.text " -=*( ENCRYPTED TALES )*=- "
.text "                 "
.text " THEY REMEMBER THE FEAR OF SAVING OVER THE WRONG DISK..."
.text " THE TRIUMPH OF SEEING YOUR OWN CODE RUN..."
.text " THE MAGIC OF MAKING A MACHINE DO SOMETHING NEW!"
.text "                 "
.text " >>> ENCRYPTED TALES IS NOT ABOUT SPEED OR BEING ELITE <<<"
.text "                 "
.text " IT IS ABOUT PRESENCE..."
.text "                 "
.text " ABOUT SITTING IN A DARK ROOM LIT ONLY BY A CRT"
.text " WITH TIME TO THINK AND SPACE TO IMAGINE..."
.text "                 "
.text " ### EACH EPISODE - A CODED CHALLENGE ###"
.text "         "
.text " ### EACH CLUE - A FRAGMENT OF DIGITAL MYTH ###"
.text "         "
.text " ### EACH REVEAL - A SECRET UNLOCKED! ###"
.text "                 "
.text " -=*( ENCRYPTED TALES )*=- "
.text "                 "
.text " FROM A TIME WHEN COMPUTERS TAUGHT US HOW TO THINK NOT JUST WHAT TO CLICK..."
.text "                 "
.text " THEY'VE BEEN WITH US FROM THE BEGINNING..."
.text "                 "
.text " THIS IS FOR THE KIDS WHO BECAME ENGINEERS..."
.text " THE HOBBYISTS WHO BECAME CREATORS..."
.text " AND THE ONES WHO NEVER STOPPED WONDERING WHAT ELSE WAS HIDING ON THAT DISK..."
.text "         "
.text " SO ADJUST THE VERTICAL HOLD, TURN UP THE VOLUME, AND LET THE SCROLL CONTINUE..."
.text "                 "
.text " -=*( ENCRYPTED TALES )*=- "
.text "                 "
.text " WHERE THE PAST BOOTS CLEAN AND THE MACHINES STILL HAVE SECRETS!"
.text "                 "
.text " IF YOU KNOW WHERE TO L@@K..."
.text "                 "
.text "                             "
.text "  CODE: DEADLINE/CXN         "
.text "                             "
.text "  SID: VANDALISM BY SPIDER J."
.text "                             "
.text "  SEE ALL THE ENCRYPTED TALES VIDEOS + PLEASE SUBSCRIBE: YOUTUBE/@CITYXEN"
.text "                             "
.text "  UNTIL NEXT TIME... L8R!"
.text "                             "
.text " -=*[ END TRANSMISSION ]*=- +++ "
.text "                             "
.byte $ff
