hello_message:
.encoding "screencode_upper"
.text "            "
.text " HI BILLY MAYS HERE - WELL SORT OF... JUST LISTEN UP! "
.text "            "
.text " ARE YOU TIRED OF JOYSTICKS THAT BREAK AFTER ONE GAME?"
.text "            "
.text " TIRED OF MISSED JUMPS . MISSED SHOTS . MISSED GLORY?"
.text "            "
.text " STOP SUFFERING AND START WINNING RIGHT NOW..."
.text "            "
.text " INTRODUCING"
.text "            -=*( RETROGAMEBOYZ.COM )*=- "
.text "            "
.text " THE MOST POWERFUL CONTROLLERS IN RETRO GAMING!              "
.text " BUILT FOR REAL MACHINES -> NOT PRETEND ONES..."
.text "            "
.text " COMMODORE . ATARI . NINTENDO . NEOGEO . VECTREX . COLECOVISION . AMSTRAD !!!"
.text "            "
.text " JUST LOOK AT THE RESPONSE TIMES! "
.text "            "
.text " PRESS FIRE * BOOM * IT FIRES! "
.text "            "
.text " MOVE LEFT * IT MOVES LEFT * "
.text "            "
.text " NO LAG... NO SLOP... NO WAITING... "
.text " THATS THE POWER OF PROPER HARDWARE!"
.text "            "
.text " OTHER CONTROLLERS ARE MADE OF SAD PLASTIC!"
.text "            "
.text " RETROGAMEBOYZ ARE MADE OF DETERMINATION..."
.text " DESIGNED BY MADMEN..."
.text "            "
.text " TESTED BY ABUSE..."
.text " IF YOU CAN BREAK IT - YOU DESERVE A MEDAL!"
.text "            "
.text " BUT WAIT... THERE'S MORE!"
.text "            "
.text " THESE CONTROLLERS LAST LONGER... "
.text " PLAY HARDER... PLAY FASTER... PLAY ANGRIER..."
.text "            "
.text " YOUR THUMB WILL GET TIRED BUT THE CONTROLLER WON'T!"
.text "            "
.text " STILL USING THAT OLD STICK?"
.text " THAT THING IS COSTING YOU POINTS DUDE!"
.text "            "
.text " COSTING YOU LIVES!"
.text "            "
.text " COSTING YOU RESPECT!"
.text "            "
.text " RETROGAMEBOYZ.COM DELIVER: PINPOINT ACCURACY -"
.text " BRICK SOLID FEEL -"
.text " AND PURE RETRO POWER!"
.text "                             "
.text " DONT DELAY - DONT THINK... "
.text " UPGRADE YOUR INPUT TODAY... "
.text " BECAUSE WINNING FEELS BETTER AND LOSING FEELS WORSE! "
.text "                             "
.text " RETROGAMEBOYZ.COM - ACCEPT NO SUBSTITUTES! "
.text " RESULTS MAY INCLUDE HIGH SCORES, FRIENDS GETTING MAD, AND UNCONTROLLED SMILING..."
.text "                             "
.text " PRESS FIRE . PLAY BETTER . REPEAT "
.text "                             "
.text " BUT WAIT... THERE'S EVEN MORE!"
.text "            "
.text " RETROGAMEBOYZ.COM CAN CREATE CUSTOM CONTROLLERS FOR WHATEVER YOU CAN IMAGINE..."
.text "            "
.text " USING THE LATEST IN 3D CREATION TOOLS, AND FABRICATED PCB TOOLS, RETROGAMEBOYZ"
.text " CAN CREATE A BRAND NEW CONTROLLER JUST FOR YOU!"
.text "                             "
.text " GET IN TOUCH AND SEE WHAT THEY CAN DO FOR YOU!"
.text "            "
.text "            -=*( RETROGAMEBOYZ.COM )*=- "
.text "            "
.text "                             "
.text "  CODE: DEADLINE/CXN         "
.text "                             "
.text "  SID: FUNK CITY BY TLF"
.text "                             "
.text " PLEASE SUBSCRIBE: YOUTUBE/@CITYXEN"
.text "                             "
.text "  THX FOR WATCHING... L8R!"
.text "                             "
.text " -=*[ END TRANSMISSION ]*=- +++ "
.text "                             "
.byte $ff
