color_table:
.byte LIGHT_GREEN, LIGHT_GREEN, LIGHT_GREEN,LIGHT_GREEN, LIGHT_GREEN 
.byte LIGHT_GREEN, LIGHT_GREEN, LIGHT_GREEN,LIGHT_GREEN, LIGHT_GREEN 
.byte LIGHT_GREEN, LIGHT_GREEN, LIGHT_GREEN, LIGHT_GREEN
.byte GREEN, GREEN
.byte LIGHT_GREY,GREY,DARK_GREY
//,BLACK
//.byte 
//BLACK,
.byte DARK_GREY,GREY,LIGHT_GREY
.byte GREEN, GREEN
.byte LIGHT_GREEN, LIGHT_GREEN, LIGHT_GREEN
.byte LIGHT_GREEN, LIGHT_GREEN, LIGHT_GREEN,LIGHT_GREEN, LIGHT_GREEN
.byte LIGHT_GREEN, LIGHT_GREEN, LIGHT_GREEN,LIGHT_GREEN, LIGHT_GREEN
.byte $ff
