color_table:
.byte RED, RED, RED,RED, RED, RED,RED, RED, RED
.byte RED, RED, RED,RED, RED, RED,RED, RED, RED
.byte LIGHT_RED, LIGHT_RED, LIGHT_RED, LIGHT_RED
.byte ORANGE, ORANGE, YELLOW, WHITE, YELLOW, ORANGE, ORANGE
.byte LIGHT_RED, LIGHT_RED, LIGHT_RED, LIGHT_RED
.byte RED, RED, RED,RED, RED, RED,RED, RED, RED
.byte RED, RED, RED,RED, RED, RED,RED, RED, RED
.byte $ff
