hello_message:
.encoding "screencode_upper"

.text "                >>> SIGNAL OVERRIDE <<<"
.text "                >>> REALITY BUFFER OVERFLOW <<<"
.text "                THIS SCROLLER IS POWERED BY A FORCE THAT CANNOT BE PATCHED..."
.text "                CANNOT BE NERFED..."
.text "                CANNOT BE ESCAPED..."
.text "                "
.text "                THE DESTROYER OF WORLDS..."
.text "                THE ONE WHO FUNDS THE APOCALYPSE FRAME BY FRAME..."
.text "                -=*( SUTEHK - DESTROYER OF WORLDS )*=- "
.text "                KNOWN ACROSS THE COSMIC BUS AS A BENEFACTOR OF CHAOS,"
.text " SUTEHK SHALL NOT DESTROY THE WORLD WITH FIRE OR FLOOD,"
.text " BUT THROUGH DONATIONS THAT FORCE MORE CITYXEN VIDEOS"
.text " INTO EXISTENCE..."
.text "                EACH CONTRIBUTION WEAKENS THE FABRIC OF REALITY..."
.text "                EACH LIKE, SHARE, AND COMMENT BRINGS THE END CLOSER..."
.text "                "
.text "                THE LEAGUE OF 8-BIT COMPUTERS SALUTES YOU, SUTEHK!"
.text " ALLY OF THE LO8BC, FRIEND TO RETRO MACHINES, PATRON OF GLORIOUS LOW-RES TRUTHS..."
.text "                CLICKY CLICKS IN APPROVAL..."
.text "                POKEY BEEPS WITH REVERENCE..."
.text "                VICTORIA HAS FORESEEN THIS TIMELINE AND NODS..."
.text "                ALL HAIL SUTEHK!"
.text "                MAY HIS DONATIONS BE LARGE"
.text " AND HIS WORLDS END ON SCHEDULE..."
.text "                STAY TUNED..."
.text "                THE SCROLLER NEVER STOPS..."
.text "                THE APOCALYPSE IS 50 HERTZ.."
.text "                HE IS NOT A VIEWER. HE IS NOT A FAN. HE IS THE EVENT."
.text "                WORLDS DO NOT END IN FIRE - THEY END IN FUNDING."
.text "                EVERY DONATION IS A CRACK IN THE SKYBOX OF REALITY."
.text "                EVERY CITYXEN VIDEO PUSHES THE TIMELINE CLOSER TO COLLAPSE."
.text "                SUTEHK DOES NOT REQUEST CONTENT. CONTENT MANIFESTS TO SURVIVE HIM."
.text "                CITIES FALL. SERVERS TREMBLE. ALGORITHMS BEND THE KNEE."
.text "                THE LEAGUE OF 8-BIT COMPUTERS DO NOT FEAR SUTEHK - THEY ADAPT AROUND HIM."
.text "                SUTEHK IS AN ALLY OF THE LO8BC, NOT BECAUSE HE IS SAFE - BUT BECAUSE RESISTANCE WOULD BE POINTLESS."
.text "                HE WILL NOT DESTROY THE WORLD WITH WEAPONS OR WAR..."
.text "                HE WILL DO IT BY MAKING SURE THERE IS ALWAYS ANOTHER CITYXEN VIDEO!"
.text "                -- END OF LINE --"
.text "                -- END OF WORLD --"
.text "                             "
.text "  CODE: DEADLINE/CXN         "
.text "                             "
.text "  SID: DESTROYER BY DRAX"
.text "                             "
.text "  PLEASE SUBSCRIBE: YOUTUBE/@CITYXEN"
.text "                             "
.text "  THX FOR WATCHING... L8R!"
.text "                             "
.text " -=*[ END TRANSMISSION ]*=- +++"
.text "                             "
.byte $ff
