color_table:
.byte BLACK, BLACK, BLACK,BLACK, BLACK 
.byte BLACK, BLACK, BLACK,BLACK, BLACK 
.byte BLACK, BLACK, BLACK, BLACK
.byte DARK_GREY,DARK_GREY
.byte GREY,GREY
.byte LIGHT_GREY,LIGHT_GREY
//.byte ORANGE, ORANGE
.byte WHITE, WHITE
//.byte ORANGE, ORANGE
.byte LIGHT_GREY,LIGHT_GREY
.byte GREY,GREY
.byte DARK_GREY,DARK_GREY
.byte BLACK, BLACK, BLACK
.byte BLACK, BLACK, BLACK,BLACK, BLACK
.byte BLACK, BLACK, BLACK,BLACK, BLACK
.byte $ff
