hello_message:
.encoding "screencode_upper"
.text "        "
.text "    -=*( OUT TO LUNCH )*=-    "
.text "        "
.text "    -=*( ADRIAN'S DIGITAL BASEMENT )*=-    "
.text "    THE LIGHTS ARE ON BUT THE OPERATOR IS TEMPORARILY AFK    "
.text "    >>> SYSTEM STATUS CHECK <<<    "
.text "    HUMAN OPERATOR HAS LEFT THE VICINITY FOR FOOD ACQUISITION    "
.text "        "
.text "    -=*( OUT TO LUNCH )*=-    "
.text "        "
.text "    OSCILLOSCOPES IN STANDBY -> LOGIC PROBES DREAMING OF BITS    "
.text "    SOLDERING IRONS COOLING DOWN AFTER A HARD DAYS WORK    "
.text "    CAPACITORS DISCHARGING -> SLOWLY -> PATIENTLY -> SAFELY    "
.text "        "
.text "    -=*( OUT TO LUNCH )*=-    "
.text "        "
.text "    THIS SCROLLER IS PROVIDED AS A PUBLIC SERVICE ANNOUNCEMENT    "
.text "    NO REPAIRS ARE CURRENTLY IN PROGRESS -> DO NOT PANIC    "
.text "    IF SOMETHING SMOKES IT WAS PROBABLY ALREADY LIKE THAT    "
.text "        "
.text "    -=*( OUT TO LUNCH )*=-    "
.text "        "
.text "    BYTES ARE RESTING WHILE BYTES ARE BEING BITTEN    "
.text "    SANDWICHES LOADING -> PLEASE WAIT -> NOM NOM NOM    "
.text "    COFFEE LEVELS CRITICAL -> LUNCH REQUIRED TO CONTINUE    "
.text "        "
.text "    -=*( OUT TO LUNCH )*=-    "
.text "        "
.text "    GREETINGS TO ALL RETRO ENTHUSIASTS WATCHING THIS SCROLL    "
.text "    GREETINGS TO BROKEN COMPUTERS WAITING THEIR TURN    "
.text "    GREETINGS TO THE ONE CAPACITOR THAT ALWAYS FAILS FIRST    "
.text "        "
.text "    -=*( OUT TO LUNCH )*=-    "
.text "        "
.text "    SHOUTOUTS TO ALL BASEMENT DWELLERS AND SILICON ARCHAEOLOGISTS    "
.text "    SHOUTOUTS TO TTL LOGIC -> ANALOG WEIRDNESS -> AND CRT GLOW    "
.text "    SHOUTOUTS TO TEST EQUIPMENT OLDER THAN THE OPERATOR    "
.text "        "
.text "    -=*( OUT TO LUNCH )*=-    "
.text "        "
.text "    IF YOU CAN READ THIS THE SCROLLER IS WORKING CORRECTLY    "
.text "    IF YOU CANNOT READ THIS ADJUST HORIZONTAL HOLD IMMEDIATELY    "
.text "    IF IT STILL FAILS TRY HITTING THE SIDE OF THE MONITOR    "
.text "        "
.text "    -=*( OUT TO LUNCH )*=-    "
.text "        "
.text "    PLEASE STAND BY FOR THE RETURN OF QUESTIONABLE REPAIRS    "
.text "    MORE VINTAGE HARDWARE WILL BE POKED SHORTLY    "
.text "    CALIBRATION WILL RESUME AT SOME UNDEFINED FUTURE TIME    "
.text "        "
.text "    -=*( OUT TO LUNCH )*=-    "
.text "        "
.text "    NORMAL SERVICE WILL RESUME...    "
.text "     EVENTUALLY    "
.text "        "
.text "        "
.byte $ff
