color_table:
.byte RED, RED, RED,RED, RED, RED,RED, RED, RED
.byte RED, RED, RED,RED, RED, RED,RED, RED, RED
.byte LIGHT_RED, LIGHT_RED, LIGHT_RED, LIGHT_RED
.byte WHITE, WHITE, WHITE, WHITE, WHITE
.byte LIGHT_RED, LIGHT_RED, LIGHT_RED, LIGHT_RED
.byte RED, RED, RED,RED, RED, RED,RED, RED, RED
.byte RED, RED, RED,RED, RED, RED,RED, RED, RED
.byte $ff