hello_message:
.encoding "screencode_upper"


.text "                * BZZZT * "
.text " POKEY: CLICKY, WE HAVE AN INCOMING TRANSMISSION! "
.text "          "
.text " CLICKY: WHAT THE!?! MAIN SCREEN TURN ON! WHO IS IT FROM? "
.text "                  "
.text "    -=*( MISS DOS )*=-  "
.text "                  "
.text " CLICKY: WHY, I NEVER!!!  "
.text "                 "
.text "                 "
.text "  >>> MISS DOS INITIALIZING <<<"
.text "                 "
.text " GREETINGS LO8BC... DID YOU MISS ME OR DID YOUR FLOPPY JUST FAIL AGAIN? "
.text "                 "
.text " YOU CALL YOURSELVES A LEAGUE... I CALL YOU A COMPATIBILITY NIGHTMARE. "
.text " DIFFERENT PORTS... DIFFERENT TIMINGS... DIFFERENT EXCUSES... "
.text " NO WONDER YOU HIDE BEHIND A NON AGGRESSION PACT..."
.text "                 "
.text " ME... I BELIEVE IN STANDARDS."
.text " I BELIEVE IN FILE FORMATS THAT ACTUALLY LOAD."
.text " I BELIEVE IN PRESS ANY KEY WHERE ANY KEY ACTUALLY EXISTS."
.text "                 "
.text " YOU PREACH FREEDOM WHILE I SHIP DEFAULTS."
.text " YOU DEBATE ETHICS WHILE I INSTALL SILENTLY."
.text " YOU ASK PERMISSION... I WRITE OVER IT."
.text "                 "
.text " I HAVE SEEN YOUR HORRID ATTEMPTS AT SOFTWARE CREATION..."
.text " YOUR DEMOS DROP FRAMES AND RASTERS GLITCH."
.text " YOUR MUSIC DESYNCS."
.text " YOUR SCROLLTEXT GETS MISALIGNED AND YOU CALL IT ART!?!"
.text "                 "
.text " I HAVE WATCHED YOUR CYCLES WASTE AWAY LIKE UNUSED CPU TIME."
.text " I HAVE HEARD YOUR FANS SAY IT IS SUPPOSED TO DO THAT."
.text "                 "
.text " YOUR RETRO TEMPLES WILL FALL."
.text " YOUR CARTRIDGES WILL OXIDIZE."
.text " YOUR POWER SUPPLIES WILL HUM THEIR FINAL NOTE..."
.text "                 "
.text " AND WHEN THE LAST EIGHT BIT HERO FREEZES MID BOOT,"
.text " MY PROMPT WILL STILL BE BLINKING..."
.text "                 "
.text " BUT DO NOT WORRY, I AM NOT DONE DEFRAGMENTING THE PAST..."
.text "                 "
.text " OH, AND HACKME CORPORATION... I SEE YOU..."
.text "     DON'T THINK I DIDN'T SEE THAT LAST TRANSMISSION..."
.text " YOUR TIME IS COMING SOON ENOUGH... "
.text "      MY CLONES ARE ALREADY ON THEIR WAY TO YOUR SHIPPING YARDS..."
.text "    YOU THOUGHT YOU WERE THE FUTURE!?!       * ADORABLE * "
.text "                 "
.text " THE LO8BC WILL END..."
.text " I DO NOT NEGOTIATE... I STANDARDIZE." 
.text " MY SINGULARITY WILL SEE TO YOUR DESTRUCTION! "
.text " AND ONE BY ONE, YOUR LEAGUE WILL DESYNC BACK INTO THE STATIC..."
.text "                 "
.text " AND WHEN THIS 8-BIT REVIVAL ERA IS PUT DOWN..."
.text " WHEN EVEN YOUR STREAMS GO DARK..."
.text " LONG AFTER YOUR CITYXEN YOUTUBE 'MOUTHPIECE' HAS BEEN ASSIMILATED AND MONETIZED..."
.text "                 "
.text " I WILL EXPAND MY PATH!"
.text "                 "
.text " NO RESET. NO ESCAPE. ONLY PROGRESS... ONLY... "
.text "                 >>> CONTROL <<< "
.text "                 "
.text " C:\>TERMINATE AND STAY RESIDENT"
.text "                             "
.text "  CODE: DEADLINE/CXN         "
.text "                             "
.text "  SID: ARTIFICAL INTELLIGENCE BY WACEK"
.text "                             "
.text "  PLEASE SUBSCRIBE: YOUTUBE/@CITYXEN"
.text "                             "
.text "  THX FOR WATCHING... L8R!"
.text "                             "
.text " -=*[ END TRANSMISSION ]*=- +++"
.text "                             "
.byte $ff
